### PR TITLE
Enable Blob serialization/deserialization

### PR DESCRIPTION
**Pull request by hatf0**
This depends on https://github.com/libmir/mir-algorithm/pull/372.

Enable Blob (de)serialization support with the new `mir.base64` module. This improves test coverage to 91.23%, and we pass every test case related to blobs.

This will also take a Mir Algorithm version bump (as it directly relies on `mir.base64`)

With this, every Ion text feature should be complete (sans shared symbol tables) 🥳

### CODE REVIEW

**Review by 9il — APPROVED** [review]

**Comment by 9il** [comment]
Plus make please overrides for 62 and 63 values. =/ aren't always valid.

**Comment by hatf0** [comment]
@9il Would you mind tagging a new release of Mir Algorithm for the base64 functionality? Would be much appreciated.

**Comment by 9il** [comment]
sure, v3.11.1. I thought you have the right to make new tags. Didn't you?

**Comment by 9il** [comment]
sorry, it is, v3.11.2

**Comment by hatf0** [comment]
> sure, v3.11.1. I thought you have the right to make new tags. Didn't you?

Oh, I do, but I was just wondering if you were waiting to create a new tag for some reason.

Anyways, thanks! I'll bump the required version of Mir Algorithm here, and then it should be ready to merge.

**Pull request merged**
