### PR TITLE
Add Ion Text parser (compatible with upstream Ion implementations)

### PR DESCRIPTION
**Pull request by hatf0**
This parser is similar to how `ion-go` parses, and as such, exhibits similar behavior (confirmed via unit-tests). It should be compliant to the Ion text parsers upstream -- but will require further testing with the `ion-tests` repo to fully confirm.

Feature list:
- [x] tokenizer (split the characters in the input range into independent tokens)
- [x] skippers (skip over values within the input range)
- [x] readers (read the contents of tokens within the input range)
- [x] unit-tests (validate functionality with upstream Ion implementations)

This PR depends on #147 being merged.

### CODE REVIEW

**Comment by hatf0** [comment]
@9il if you could review this -- I don't think that it's ready to merge *as-is*, but I'd love any and all input. It should be relatively trivial to fully connect Ion text and attaching it to the binary representation.

I can minimize GC usage in this if requested -- just let me know.

**Comment by 9il** [comment]
Awesome! That is really great. I will do a proper review. Few nitpicks for now:
1. Please use spaces instead of tabs. Sometimes there are tabs. There are additional leading spaces in the comments.
2. Please reduce the number of `std.*` imports. For example, if cast a char to ubyte, just `cast(ubyte)` can be used. See also what std modules are used by other mir-ion and mir-algorithm code.
3. We should support UTF-8, support for the other encodings is optional. It is very desired to support it without using Unicode tables and/or std.utf. However, for the first release, we can use std.utf/std.uni if required for simplicity.
4. Please add the information about the author to each module you have added. 
5. `std.format` is undesired. See also [mir.format](http://mir-algorithm.libmir.org/mir_format.html) and [mir.exception](http://mir-algorithm.libmir.org/mir_exception.html). Mir exceptions and mir.format can format the arguments using the stack memory.

Thank you!

**Comment by hatf0** [comment]
I believe I've addressed 1, 2, 4, and 5 with those commits above.

Would you mind clarifying for 3 -- where should UTF-8 support exist (if not already present)?

**Comment by 9il** [comment]
Thanks! I need to finish #146 and rebase your PR on it. I plan to work on it this weekend.

**Comment by 9il** [comment]
@hatf0 I have added you to the gihub libmir organization.  The PR review is in #153

**Pull request merged**
