### PR TITLE
De-genericify lexer and clarify std.range imports

### PR DESCRIPTION
**Pull request by hatf0**
This should address points 1 and 3 from #153. Working on point 2.

### CODE REVIEW

**Comment by 9il** [comment]
`ScopedBuffer` is stack/heap-allocated and its `data` is destroyed out of the scope.

The 1. is about to assume that the input is a string.

For example, this should be:
```d
const(char)[] readTimestamp(T)(ref T t)
```

```d
 //@nogc is optional. See also MirException and DIP1008
const(char)[] readTimestamp(return ref const(char)[] text) @safe pure @nogc
```

This allows to do not allocated the result. Note, that ScopedBuffer is destroyed on exit. So, the valid expression is `return buffer.data.idup`. The idea is to use the buffer only for strings and only if the string contains escaped characters. In the example above, `readTimestamp` returns the slice of the input `text` and doesn't need to use a buffer.

Furthermore, it doesn't need to make a full timestamp or number validation because this can be done on the next stage.

This simplifies the code and makes it one-two orders of magnitude faster.

**Comment by hatf0** [comment]
Re: full timestamp/number validation. That sounds good to me! I was more or less trying to keep functionality inline with upstream Ion implementations, but I'm open to refactoring the reading primitives and moving the validation to higher-levels.

Re: ScopedBuffer going out of scope, I wasn't aware of that! I guess it is in the name, but I wasn't entirely okay with the idea of `idup` being thrown all over the place. I'll add it back in.

**Comment by hatf0** [comment]
I do have one question with making the code *less* generic: does that come with ditching the entire idea that the tokenizer will take in a (theoretically infinite) input range? Since slicing is *not guaranteed* for all input/forward ranges, I tried to avoid it and go the safer route of reading/parsing lazily, which is not too dissimilar to how it is done upstream.

So I'm a little wary on this - I'd love some more clarification.

**Comment by 9il** [comment]
Generic doesn't mean performant. You can be sure that UTF-16/UTF-32 conversion to UTF-8 + @nogc UTF-8 parsing based on slicing would be executed much faster than lazy UTF-16/UTF-32 parsing with tokens allocation.

Another issue is that you may want to have a lazy parser to minimize the maximum required memory. It is actual for newline-separated JSON logs, which may weigh gigabytes. For these text monsters, we can adopt the SIMD JSON parser implemented in mir-ion. On another hand, the text version of Ion is very unlikely will be used for huge data files. For this  JSONL or binary Ion can be used instead.

> does not sit all too well with me

What is your use case?

**Comment by hatf0** [comment]
Hm. That is very true, I hadn't considered that.

How about a compromise here? I have two ideas:
1. Maintaining the current API, but changing the functions to be `@nogc` and refactoring them to return exclusively slices from the internal input range  
2. Changing the API, and refactoring the readers to be more generic. This would mean that these readers would exclusively operate on a const(char)[] buf (similarly to what you posted) and return the matching item. These readers would ideally be wrapped within the tokenizer (so you don't need to deal with maintaining state)

**Comment by 9il** [comment]
> How about a compromise here? I have two ideas:

Could you please give few API examples? I am not sure I got it right.

**Comment by hatf0** [comment]
I was thinking about just (as you suggested):
```
const(char)[] readTimestamp(return ref const(char)[] text) @safe pure @nogc
```
and then within the IonTokenizer class:
```
const(char)[] readTimestamp() @safe pure @nogc
```

I've been attacking this for the past few days and I've run into one huge snag: normalization of CRLF.. How do we normalize CRLF to just a NL without invoking GC? Replace all instances of CRLFs with NLs?

**Comment by hatf0** [comment]
I've just tackled this issue with replacing any instances of CRLF or just plain CR with LF/NL (which should be spec). The tokenizer itself does no GC allocation (other then the ctor and corresponding helper functions -- this should be easy to strip out later), and I'm working on getting the readers to be the same.

**Comment by 9il** [comment]
It’s possible to make it nogc if it represent string by parts.

**Comment by hatf0** [comment]
Can you clarify what you mean by "parts"? Do you mean like, creating a struct with the matched text? I think that would still require an allocation regardless (as we'd have to allocate the buffer to hold the matched text for further transformation)

**Comment by 9il** [comment]
BTW, scoped-buffer uses `malloc` if it is out of stack space.
However, with a @nogc design, we don't need it in the readers and tokenizer.

The readers may return a string by parts. It is fine because ion binary tape construction API allows it.
If the reader/tokenizer (it all the same thing in my head) find CRCF sequence or escaped sequence it encodes it to `Tokenizer.encodedEscapedSequence` buffer and returns a slice of it. We don't need the whole encoded string.  It is fine to return it part-by-part.

```d
struct IonTextToken
{
     // slice of the IonTokenizer.input OR
     // a slice of the IonTokenizer.encodedEscapedSequence
      const(char)[] matchingText;
      // true if it is a not fiunal string part.
      bool notFinal;
}
```

```d

// Not a generic struct!
struct IonTokenizer
{
    const(char)[] input;

    // Encoded escaped sequence in UTF-8
    char[6] encodedEscapedSequence;

    bool finished;

    size_t position;

    IonTokenType currentToken;

    this(const(char)[] input) @safe pure nothrow @nogc
    {
        this.input = input;
    }
...
```

**Comment by 9il** [comment]
@hatf0 any help I can do for MR?

**Comment by hatf0** [comment]
Sorry - life has been a little hectic recently. I'll take a look at this and try and get it all figured out (by this weekend, hopefully).

**Comment by hatf0** [comment]
Sorry about the delay. I'll be taking a look at this PR and have it return bit-by-bit.

**Comment by hatf0** [comment]
Hey! I have an example working for this. Let me know if this is okay:
```d
  void testMultiPart(string ts, string expected, string after, char last) {
      auto t = tokenizeString(ts);
      assert(t.nextToken());
      assert(t.currentToken == IonTokenType.TokenString);

      auto str = t.readString();
      assert(str.matchedText == expected);
      assert(!str.isEscapeSequence);
      assert(!str.isFinal);

      auto str2 = t.readString();
      assert(str2.matchedText == after);
      assert(str2.isEscapeSequence);
      assert(!str2.isFinal);

      auto str3 = t.readString();
      assert(str3.matchedText == "");
      assert(!str3.isEscapeSequence);
      assert(str3.isFinal);
      assert(t.readInput() == last);
  }

testMultiPart(`"Hello! \U0001F44D"`, "Hello!", "👍", 0);
```

In this example, you are expected to consume until readString().isFinal == true

**Comment by 9il** [comment]
Great! One nitpick: str2 is already final:

```d
  void testMultiPart(string ts, string expected, string after, char last) {
      auto t = tokenizeString(ts);
      assert(t.nextToken());
      assert(t.currentToken == IonTokenType.TokenString);

      auto str = t.readString();
      assert(str.matchedText == expected);
      assert(!str.isEscapeSequence);
      assert(!str.isFinal);

      auto str2 = t.readString();
      assert(str2.matchedText == after);
      assert(str2.isEscapeSequence);
      assert(str2.isFinal);
  }
```

**Comment by hatf0** [comment]
Great! I've fixed that. One thing that this does break is the implicit concatenation of long-strings, though. You can see this here:
```d
  void test(string ts, string expected, char after) {
      auto t = tokenizeString(ts);
      assert(t.nextToken());
      assert(t.currentToken == IonTokenType.TokenLongString);
      auto str = t.readLongString();
      assert(str.matchedText == expected);
      assert(t.readInput() == after);
      assert(str.isFinal);
  }

  void testMultiPart(string ts, string expected1, string expected2, char after) {
      auto t = tokenizeString(ts);
      assert(t.nextToken());
      assert(t.currentToken == IonTokenType.TokenLongString);
      auto str = t.readLongString();
      assert(str.matchedText == expected1);
      assert(str.isFinal);

      assert(t.nextToken());
      assert(t.currentToken == IonTokenType.TokenLongString);
      auto str2 = t.readLongString();
      assert(str2.matchedText == expected2);
      assert(t.readInput() == after);
      assert(str.isFinal);
  }

  test(`'''Hello, world'''`, "Hello, world", 0);
  testMultiPart(`'''Hello! ''''''\U0001F44D'''`, "Hello! ", "👍", 0);
  test(`'''0xFOOBAR''',`, "0xFOOBAR", ',');
  test(`'''Hello, 'world'!'''`, "Hello, \'world\'!", 0);
  testMultiPart(`'''Hello,'''''' world!'''`, "Hello,", " world!", 0); // note the use of testMultiPart here
  testMultiPart(`'''Hello,'''     ''' world!'''`, "Hello,", " world!", 0); // note the use of testMultiPart here
  ```

**Comment by 9il** [comment]
Awesome.

The tokenizer can work with a `const(char)[]` directly, instead of `ubyte` array. Also, we don't need to duplicate the data. `const(char)[]` should be used everywhere here for input or its slice or slice of a tokenizer buffer.

**Comment by 9il** [comment]
You can ignore CI failures on old compilers

**Comment by hatf0** [comment]
Sounds good. I have the vast majority of the tokenizer converted to `@nogc @safe pure`. The only time that a GC allocation is required is with the replacement of CRLF to LF (and CR to LF), and I doubt this is avoidable. Everything else has been converted over (and returns by parts!)

**Comment by 9il** [comment]
> Sounds good. I have the vast majority of the tokenizer converted to `@nogc @safe pure`. The only time that a GC allocation is required is with the replacement of CRLF to LF (and CR to LF). This is avoidable - the user should know if their data is normalized to Unix-endings, but for compatibility sake it remains. Everything else has been converted over (and returns by parts!)

Ion specifies newlines normalization only for long strings. For other strings, newlines are either aren't allowed by spec or we can do not care about them. Could you please add built-in @nogc long string line CRLF to LF (and CR to LF) chunking the same way as for escape sequence?

**Comment by hatf0** [comment]
> > Sounds good. I have the vast majority of the tokenizer converted to `@nogc @safe pure`. The only time that a GC allocation is required is with the replacement of CRLF to LF (and CR to LF). This is avoidable - the user should know if their data is normalized to Unix-endings, but for compatibility sake it remains. Everything else has been converted over (and returns by parts!)
> 
> Ion specifies newlines normalization only for long strings. For other strings, newlines are either aren't allowed by spec or we can do not care about them. Could you please add built-in @nogc long string line CRLF to LF (and CR to LF) chunking the same way as for escape sequence?

Hm. According to the ANTLR spec, CRLF is treated as a regular new-line, so I've removed all cases where we normally fail. This makes the core function `@nogc`, with the only exception being the UTF-16/UTF-32 overloads. 

This previous commit does normalization for long strings (and explicitly long strings). CRLF/LF is consumed, and a new-line is placed in a result. The semantics are virtually identical to how escape sequences are handled - it will return `isFinal == true` if a CRLF/LF precedes the end of the string. See:
 https://github.com/libmir/mir-ion/blob/60180c6bf1fa6536821feecaa411008f505bbbb1/source/mir/ion/deser/text/readers.d#L684-L688

**Comment by 9il** [comment]
Thanks, merged!

**Pull request merged**
